[package]
name = "r_spec1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
eframe = "0.25.0"
egui = "0.25.0"
egui_plot = "0.25.0"
rand = "0.8.5"
rppal = "0.16.1"
